In [2]:
import numpy as np

In [3]:
np.ones((10,5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [5]:
#NumPy dtype Hierarchy

In [6]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)

In [7]:
np.issubdtype(ints.dtype, np.integer)

True

In [8]:
np.issubdtype(floats.dtype, np.floating)

True

In [9]:
#see all of the parent classes of a specific dtype by calling the type’s mro method
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [10]:
#Reshaping Arrays

In [11]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [13]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
arr = np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [16]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
#C versus Fortran Order

In [21]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
#Fortran order:Fortran / column major order: traverse higher dimensions last (e.g. axis 0 before advancing on axis 1)
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [24]:
#Concatenating and Splitting Arrays

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [26]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [28]:
np.vstack((arr1, arr2))  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [30]:
from numpy.random import randn

In [31]:
arr = randn(5, 2) 
arr

array([[ 1.53299873,  1.20923202],
       [-1.24903326, -0.96809215],
       [-0.52205414, -1.82546838],
       [-0.3592519 ,  0.87443861],
       [-0.00896954,  0.16579499]])

In [32]:
first, second, third = np.split(arr, [1, 3])

In [33]:
first

array([[1.53299873, 1.20923202]])

In [34]:
second

array([[-1.24903326, -0.96809215],
       [-0.52205414, -1.82546838]])

In [35]:
third

array([[-0.3592519 ,  0.87443861],
       [-0.00896954,  0.16579499]])

In [36]:
arr = np.arange(6)

In [37]:
arr1=arr.reshape((3,2))
arr2=randn(3,2)

In [38]:
#r_ and c_ means rows and columns
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-2.10651361,  0.11168289],
       [ 0.3353158 , -1.76601786],
       [ 0.36135866,  0.86750092]])

In [39]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-2.10651361,  0.11168289,  3.        ],
       [ 0.3353158 , -1.76601786,  4.        ],
       [ 0.36135866,  0.86750092,  5.        ]])

In [40]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [41]:
arr=np.arange(3)

In [42]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [43]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [44]:
arr = randn(2, 2)
arr

array([[ 0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423]])

In [45]:
arr.repeat(2, axis=0)

array([[ 0.1982513 , -1.59619415],
       [ 0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423],
       [-0.12291038,  1.85755423]])

In [46]:
arr.repeat(2, axis=1)

array([[ 0.1982513 ,  0.1982513 , -1.59619415, -1.59619415],
       [-0.12291038, -0.12291038,  1.85755423,  1.85755423]])

In [47]:
arr.repeat([2, 3], axis=0)

array([[ 0.1982513 , -1.59619415],
       [ 0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423],
       [-0.12291038,  1.85755423],
       [-0.12291038,  1.85755423]])

In [48]:
arr.repeat([2, 3], axis=1)

array([[ 0.1982513 ,  0.1982513 , -1.59619415, -1.59619415, -1.59619415],
       [-0.12291038, -0.12291038,  1.85755423,  1.85755423,  1.85755423]])

In [49]:
arr

array([[ 0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423]])

In [50]:
np.tile(arr, 2)

array([[ 0.1982513 , -1.59619415,  0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423, -0.12291038,  1.85755423]])

In [51]:
np.tile(arr, (3, 2)) 

array([[ 0.1982513 , -1.59619415,  0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423, -0.12291038,  1.85755423],
       [ 0.1982513 , -1.59619415,  0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423, -0.12291038,  1.85755423],
       [ 0.1982513 , -1.59619415,  0.1982513 , -1.59619415],
       [-0.12291038,  1.85755423, -0.12291038,  1.85755423]])

In [52]:
#Fancy Indexing Equivalents: Take and Put

In [53]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6] 
arr[inds]

array([700, 100, 200, 600])

In [54]:
arr.take(inds)

array([700, 100, 200, 600])

In [55]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [56]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [57]:
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr

array([[ 0.36690934,  1.46515809,  0.56082398,  0.70189722],
       [-0.1298453 , -1.31266755, -0.81616601,  0.50783994]])

In [58]:
arr.take(inds, axis=1)

array([[ 0.56082398,  0.36690934,  0.56082398,  1.46515809],
       [-0.81616601, -0.1298453 , -0.81616601, -1.31266755]])

In [59]:
arr = randn(1000, 50)
# Random sample of 500 rows
inds = np.random.permutation(1000)[:500]

In [60]:
%timeit arr[inds]

20.1 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [61]:
%time arr.take(inds,axis=0)

CPU times: user 169 µs, sys: 74 µs, total: 243 µs
Wall time: 160 µs


array([[-0.88117691,  1.75927058, -0.26074162, ..., -1.3391731 ,
        -0.59804029,  0.03727483],
       [-0.21266014,  1.74876346,  1.12792673, ..., -0.36250292,
         0.21796802, -1.65850107],
       [ 0.73934897,  0.65084954, -0.72335561, ...,  0.64025565,
         0.86305475, -1.77640214],
       ...,
       [-0.67194614, -0.32417443, -1.23752474, ...,  1.35297968,
        -1.46783748,  0.2672611 ],
       [-0.11061548,  0.09740096, -0.91400389, ..., -1.44457842,
        -0.58200142, -0.06045743],
       [-0.28251204,  1.31010438,  0.17424309, ..., -0.46774776,
        -0.28563725,  1.10529112]])

In [62]:
arr = np.arange(5)
arr*4

array([ 0,  4,  8, 12, 16])

In [63]:
arr=np.arange(10)


In [64]:
np.add.reduce(arr)

45

In [65]:
arr.sum()

45

In [67]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [68]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [69]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [73]:
result = np.subtract.outer(randn(3, 4), randn(5))
result

array([[[-3.54410486, -1.19272785, -3.20599956, -0.46985375,
         -1.67513878],
        [-2.5239576 , -0.17258058, -2.1858523 ,  0.55029351,
         -0.65499152],
        [-3.38248797, -1.03111096, -3.04438267, -0.30823686,
         -1.51352189],
        [-2.6243098 , -0.27293279, -2.2862045 ,  0.44994131,
         -0.75534372]],

       [[-1.003607  ,  1.34777001, -0.6655017 ,  2.07064411,
          0.86535908],
        [-2.48311699, -0.13173998, -2.14501169,  0.59113412,
         -0.61415091],
        [-1.72426448,  0.62711253, -1.38615918,  1.34998663,
          0.1447016 ],
        [-2.09769583,  0.25368119, -1.75959053,  0.97655528,
         -0.22872975]],

       [[-3.87921916, -1.52784214, -3.54111386, -0.80496805,
         -2.01025308],
        [-3.85833592, -1.50695891, -3.52023062, -0.78408481,
         -1.98936984],
        [-2.09622838,  0.25514863, -1.75812308,  0.97802273,
         -0.2272623 ],
        [-4.47711131, -2.1257343 , -4.13900601, -1.4028602 ,
         -2

In [74]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# The results are the reductions (here, sums) performed over arr[0:5], arr[5:8], and arr[8:]. 
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [77]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [78]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [79]:
#Custom ufuncs

In [80]:
def add_elements(x, y):
   return x + y

In [81]:
# number of input and outputs: 2 and 1
add_them = np.frompyfunc(add_elements, 2, 1)

In [82]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [83]:
#numpy.vectorize that is a bit more intelligent about type inference than np.frompyfunc
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [84]:
arr = randn(10000)


In [85]:
%timeit add_them(arr, arr)

1.39 ms ± 64.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
%timeit np.add(arr, arr)

5.94 µs ± 41.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [87]:
#Structured and Record Arrays

In [88]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [89]:
sarr[0]

(1.5, 6)

In [90]:
sarr[0]['y']


6

In [93]:
sarr['x']

array([1.5       , 3.14159265])

In [94]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [95]:
arr[0]['x']

array([0, 0, 0])

In [96]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [97]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [98]:
data['y']

array([5, 6], dtype=int32)

In [99]:
data['x']['a']

array([1., 3.])

In [101]:
arr = randn(6)
arr.sort()
arr

array([-0.93756451, -0.781724  , -0.75822163,  0.27136456,  0.98823108,
        2.19845391])

In [106]:
arr = randn(3, 5)
arr

array([[ 0.91044996,  0.1005629 ,  0.86890663, -0.10499224,  2.45304234],
       [ 0.01100208, -0.97349924,  0.73547934, -0.78122457,  1.24831367],
       [ 0.6315086 ,  1.41651019, -0.20023813, -0.1429593 , -2.3495089 ]])

In [108]:
arr[:, 0].sort()  # Sort first column values in-place
arr

array([[ 0.01100208,  0.1005629 ,  0.86890663, -0.10499224,  2.45304234],
       [ 0.6315086 , -0.97349924,  0.73547934, -0.78122457,  1.24831367],
       [ 0.91044996,  1.41651019, -0.20023813, -0.1429593 , -2.3495089 ]])

In [109]:
arr = randn(5)
arr

array([-0.60285276, -0.14066231,  0.81075266,  0.27020816,  0.20020347])

In [110]:
np.sort(arr)

array([-0.60285276, -0.14066231,  0.20020347,  0.27020816,  0.81075266])

In [111]:
arr

array([-0.60285276, -0.14066231,  0.81075266,  0.27020816,  0.20020347])

In [112]:
arr = randn(3, 5)
arr

array([[-0.24173111, -0.1717546 , -1.18611748,  0.52701422, -0.57467063],
       [ 1.37028057,  0.70124886,  0.76085428,  0.75279929, -0.8735933 ],
       [ 1.25881038, -0.07990233,  2.18921182,  0.98908107, -1.56483872]])

In [114]:
arr.sort(axis=1)
arr

array([[-1.18611748, -0.57467063, -0.24173111, -0.1717546 ,  0.52701422],
       [-0.8735933 ,  0.70124886,  0.75279929,  0.76085428,  1.37028057],
       [-1.56483872, -0.07990233,  0.98908107,  1.25881038,  2.18921182]])

In [115]:
arr[:, ::-1]

array([[ 0.52701422, -0.1717546 , -0.24173111, -0.57467063, -1.18611748],
       [ 1.37028057,  0.76085428,  0.75279929,  0.70124886, -0.8735933 ],
       [ 2.18921182,  1.25881038,  0.98908107, -0.07990233, -1.56483872]])

In [116]:
values = np.array([5, 0, 1, 3, 2])

In [118]:
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [119]:
values[indexer]

array([0, 1, 2, 3, 5])

In [121]:
arr = randn(3, 5)
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.01093775,  0.5444965 , -0.56121448, -0.7391112 , -0.56813092],
       [ 0.66010615,  0.21333153,  0.48710869,  2.81309669,  0.49893227]])

In [122]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.5444965 , -0.56121448, -0.56813092, -0.7391112 , -0.01093775],
       [ 0.21333153,  0.48710869,  0.49893227,  2.81309669,  0.66010615]])

In [127]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

In [138]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [139]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [140]:
#numpy.searchsorted: Finding elements in a Sorted Array
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [141]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [142]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])

arr.searchsorted([0, 1])

array([0, 3])

In [143]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [144]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([7590., 1380., 4564., 9874., 4907., 3807., 5946., 2113., 1359.,
       2950., 7875.,  626., 5617., 8083., 2471., 3821., 2338.,  839.,
       7136., 9426., 2940.,  781., 4564., 9091., 2927., 2273., 7978.,
       5674., 1608., 8511., 8882.,  436., 5404., 7353., 2690., 9629.,
       2782., 8781., 4895., 2023., 7236., 2640., 5076., 1284., 1214.,
       6357.,  441., 9923., 1264., 2546.])

In [146]:
labels = bins.searchsorted(data)
labels

array([4, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 2, 4, 4, 3, 3, 3, 2, 4, 4, 3, 2,
       3, 4, 3, 3, 4, 4, 3, 4, 4, 2, 4, 4, 3, 4, 3, 4, 3, 3, 4, 3, 4, 3,
       3, 4, 2, 4, 3, 3])

In [148]:
from pandas import Series

In [149]:
Series(data).groupby(labels).mean()

2     624.600000
3    2723.333333
4    7687.714286
dtype: float64

In [150]:
# NumPy actually has a function digitize that computes this bin labeling
np.digitize(data, bins)

array([4, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 2, 4, 4, 3, 3, 3, 2, 4, 4, 3, 2,
       3, 4, 3, 3, 4, 4, 3, 4, 4, 2, 4, 4, 3, 4, 3, 4, 3, 3, 4, 3, 4, 3,
       3, 4, 2, 4, 3, 3])

In [151]:
#NumPy Matrix Class

In [152]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
   [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
   [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
   [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [153]:
X[:, 0]  # one-dimensional

array([ 8.82768214,  3.82222409, -1.14276475,  2.04411587])

In [156]:
y = X[:, :1]  # two-dimensional by slicing
y

array([[ 8.82768214],
       [ 3.82222409],
       [-1.14276475],
       [ 2.04411587]])

In [157]:
np.dot(y.T, np.dot(X, y))

array([[1195.46796121]])

In [158]:
Xm = np.matrix(X)
ym = Xm[:, 0]

In [159]:
Xm

matrix([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
        [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
        [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
        [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [160]:
ym

matrix([[ 8.82768214],
        [ 3.82222409],
        [-1.14276475],
        [ 2.04411587]])

In [161]:
ym.T * Xm * ym

matrix([[1195.46796121]])

In [162]:
Xm.I * X

matrix([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17,
          5.55111512e-17],
        [-1.11022302e-16,  1.00000000e+00,  2.77555756e-17,
         -5.55111512e-17],
        [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [-5.55111512e-17, -5.55111512e-17,  2.77555756e-17,
          1.00000000e+00]])

In [167]:
#Advanced Array Input and Output

In [169]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [170]:
section = mmap[:5]
section

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [171]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap

memmap([[ 0.81800755,  0.98745683, -0.59528545, ...,  2.280353  ,
         -0.80971319, -0.79731251],
        [ 0.75601483,  0.91305535, -0.85692389, ..., -0.59981535,
          0.12880062, -0.49769731],
        [-1.0485276 ,  0.35841157, -0.41017854, ...,  0.54017842,
          0.88647029, -0.26085503],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [172]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')

In [173]:
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [174]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [175]:
arr_f.flags.f_contiguous

True

In [176]:
%timeit arr_c.sum(1)

414 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [177]:
%timeit arr_f.sum(1)

646 µs ± 12.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [178]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [179]:
arr_c[:50].flags.contiguous 

True

In [180]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Object ` cimport` not found.
